import type { Metadata } from 'next'
import Recoil from "@/recoil";
import ReactQuery from "@/react-query";
import React from "react";

export const metadata: Metadata = {
  title: 'Next App',
  description: 'Generated by create next app',
}

const  RootLayout=({
  children,
}: {
  children: React.ReactNode
})=> {
  return (
    <html lang="en">
      <body>
      <Recoil><ReactQuery>
      <nav>
      hello?
      </nav>
      {children}
      </ReactQuery>
      </Recoil>
      </body>
    </html>
  )
}

export default RootLayout;
